<a href="https://colab.research.google.com/github/krishnamani77/TF2_Notebooks/blob/master/Sentiment-analysis-IMDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import keras
import keras.datasets

Using TensorFlow backend.


In [2]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [3]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 7176275123603679013, name: "/device:XLA_CPU:0"
 device_type: "XLA_CPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 7947802596328587402
 physical_device_desc: "device: XLA_CPU device", name: "/device:XLA_GPU:0"
 device_type: "XLA_GPU"
 memory_limit: 17179869184
 locality {
 }
 incarnation: 7417804228162051161
 physical_device_desc: "device: XLA_GPU device", name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 14648777152
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 1990859460569813184
 physical_device_desc: "device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5"]

In [4]:
!cat /proc/meminfo

MemTotal:       13333556 kB
MemFree:         9185104 kB
MemAvailable:   11826500 kB
Buffers:           77288 kB
Cached:          2705712 kB
SwapCached:            0 kB
Active:          1267752 kB
Inactive:        2480940 kB
Active(anon):     922392 kB
Inactive(anon):     8536 kB
Active(file):     345360 kB
Inactive(file):  2472404 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               544 kB
Writeback:             0 kB
AnonPages:        965792 kB
Mapped:           650788 kB
Shmem:              9140 kB
Slab:             174244 kB
SReclaimable:     129044 kB
SUnreclaim:        45200 kB
KernelStack:        3876 kB
PageTables:         8652 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6666776 kB
Committed_AS:    3192096 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:              920 kB
AnonHugePages:   

In [5]:
# IMDB Sentiment analysis
(X_train, y_train), (X_test, y_test) = keras.datasets.imdb.load_data(num_words=10000)

17465344/17464789 [==============================] - 1s 0us/step


In [6]:
word_index = keras.datasets.imdb.get_word_index()
reverse_index = {}
for k, v in word_index.items():
  reverse_index[v+3] = k

1646592/1641221 [==============================] - 1s 0us/step


In [7]:
print(len(word_index), len(reverse_index))

88584 88584


In [8]:
print(X_train[0])
print(y_train[:10])
print(y_train[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
[1 0 0 1 0 0 1 0 1 0]
1


In [9]:
print(X_train[0].__class__)
print(y_train[0].__class__)

<class 'list'>
<class 'numpy.int64'>


In [0]:
for id, token in enumerate(("<pad>", "<sos>", "<unk")):
  reverse_index[id] = token

In [13]:
s = ' '.join([reverse_index[idx] for idx in X_train[0][:10]])

print(s)

<sos> this film was just brilliant casting location scenery story


In [0]:
vocab_size = len(word_index)

In [0]:
import numpy as np
def vectorize(sequences, dimension = 10000):
  results = np.zeros((len(sequences), dimension))
  for i, sequence in enumerate(sequences):
    results[i, sequence] = 1
  return results

X_train = vectorize(X_train, 10000)
y_train = np.array(y_train).astype("float32")
X_test = vectorize(X_test, 10000)
y_test = np.array(y_test).astype("float32")

In [16]:
print(X_train[0])
print(y_train[:10])

[0. 1. 1. ... 0. 0. 0.]
[1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]


In [21]:
from keras.models import Sequential
from keras.layers import Embedding, GRU, Dense

embed_size = 128
embedding = Embedding(vocab_size, embed_size, input_shape=(10000, ))
hidden1 = GRU(128, return_sequences = True)
hidden2 = GRU(128)
dense = Dense(1, activation='sigmoid')
model = Sequential([embedding, hidden1, hidden2, dense])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
history = model.fit(X_train, y_train, batch_size=1024, epochs=5)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/5


ResourceExhaustedError: ignored